import type { Metadata } from "next";
import { Geist, Geist_Mono, Nabla, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${montserrat.className} bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
